### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Nucito** [Tugcga/SmartFox-Python-Communicator#1]
I try to import the package but i get a error:

`ImportError: DLL load failed while importing SFSCommunicator: The specified module could not be found.`

yes i put the dll in the same path of the .pyd file

**Comment by Tugcga** [comment]
Check that you actually use Python 3.6. If your version of the Python is different, then the module can not be imported. I add module files, compiled for Python 3.9 and 3.10, to the release page (https://github.com/Tugcga/SmartFox-Python-Communicator/releases). May be some of them will works.

**Comment by Nucito** [comment]
Sorry for my error i'm using py 3.9 😅
Thx for the new update, works perfectly.

**Comment by Nucito** [comment]
It's possible to start a new object DataContainer and put raw data into it?

Example:

```python3
data = bytes.fromhex("800080120003000163020100016103000d00017012000300016308000950494e475f504f4e4700017204ffffffff0001701200040004646174611200000002696404000000700004686173680800203964666435633765633731393636363338656633323233623830613662666437000974696d657374616d700500003a079021d855")
```

I need put this to after get the values with the methods of SFSObject like get_byte and get_int.

**Comment by Tugcga** [comment]
If you asks about serialization and deserialization of the data container object, then no, it is not supported.

You can create a new data container in the following way:
```
data: sfs.DataContainer = sfs.DataContainer()
```
Then add value to it:
```
data.put_float("posX", pos_x)
```
In the same way you can use ```put_int```, ```put_bool``` and ```put_byte```. Byte in the last command is one unsigned char value. In the Python side it always integer, but in the c++ side it size is only one byte.

Then you can send the data container to the server:
```
client.send_command("command name", data)
```

**Comment by Nucito** [comment]
Thx for the help 😃
